# Generated by Django 4.2.30 on 2026-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsession',
            old_name='total_hesitations',
            new_name='fast_answer_count',
        ),
        migrations.RenameField(
            model_name='quizsession',
            old_name='decision_style',
            new_name='predicted_style',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='hesitation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='hesitation_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='max_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='median_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='min_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='slow_answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='std_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
